[Variables]
;=========================================;
;===========Set These Variables===========;
;=========================================;

;Choose latitude and longitude of your location
WeatherLat=25.86
WeatherLon=-80.26

;Choose your Units: F, C;
WeatherUnit=F

;Region
WeatherRegion=US

;Set Your Maximum Upload Speed Here;
NetworkMaxUp=10950000

;Set your Maximum Download Speed Here;
NetworkMaxDown=790000

;===========Other===========;
ProcessInterval=5
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":""
Day="0":"SUN","1":"MON","2":"TUE","3":"WED","4":"THU","5":"FRI","6":"SAT"